# OpenCode (Azure Foundry edition) — container for Azure VNet deployment.
FROM node:20-bookworm-slim AS build
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci
COPY tsconfig.json ./
COPY src ./src
RUN npm run build

FROM node:20-bookworm-slim AS runtime
WORKDIR /app
ENV NODE_ENV=production
COPY package.json package-lock.json ./
RUN npm ci --omit=dev
COPY --from=build /app/dist ./dist
# opencode.json is generated by `npm run setup` and provided at deploy time
# (mount it, bake it in, or supply the equivalent AZURE_* env vars).
# Secrets come from the environment (Key Vault refs in Azure), not this image.
EXPOSE 3000
CMD ["node", "dist/server.js"]
