/*
 * OpenCode + Daytona launcher — Azure Foundry edition (firm internal).
 * ------------------------------------------------------------------
 * Designed to run INSIDE an Azure VNet that can reach a private Azure AI
 * Foundry endpoint. Launches OpenCode Web inside on-demand (self-hosted)
 * Daytona sandboxes, with OpenCode defaulted to the firm's Azure Foundry
 * deployment(s).
 *
 * Auth model (Entra-primary, no API keys for end users):
 *  - App access: lightweight Entra SSO (corporate Microsoft sign-in).
 *  - Foundry calls: Entra managed identity token (no Foundry API key passed),
 *    acquired at sandbox launch and injected into the sandbox. API-key fallback
 *    supported only if the operator opts out of managed identity at setup.
 *
 * Configuration is baked in at install time by `npm run setup` (writes a
 * gitignored .env and an opencode.json). This server just reads that config.
 */

import express, { NextFunction, Request, Response } from 'express'
import crypto from 'node:crypto'
import fs from 'node:fs'
import path from 'node:path'
import { Daytona, Sandbox } from '@daytona/sdk'
import { DefaultAzureCredential } from '@azure/identity'
import { ConfidentialClientApplication } from '@azure/msal-node'

// ---------------------------------------------------------------------------
// Config (from environment, populated by setup.mjs into .env)
// ---------------------------------------------------------------------------
const PORT = parseInt(process.env.PORT || '3000', 10)
const OPENCODE_PORT = 3000
const OPENCODE_VERSION = process.env.OPENCODE_VERSION || '1.17.3'
const SANDBOX_IMAGE = process.env.SANDBOX_IMAGE || 'node:20'
const APP_LABEL = 'opencode-foundry'

// --- Self-hosted Daytona ---
const DAYTONA_API_KEY = process.env.DAYTONA_API_KEY || ''
// Self-hosted Daytona control-plane base URL (NOT app.daytona.io).
const DAYTONA_API_URL = process.env.DAYTONA_API_URL || ''
const DAYTONA_TARGET = process.env.DAYTONA_TARGET || ''

// --- Azure Foundry ---
const AZURE_FOUNDRY_BASE_URL = process.env.AZURE_FOUNDRY_BASE_URL || '' // e.g. https://my-res.services.ai.azure.com
const AZURE_API_VERSION = process.env.AZURE_API_VERSION || '' // e.g. 2025-04-01-preview, or empty for v1 GA
const AZURE_DEFAULT_DEPLOYMENT = process.env.AZURE_DEFAULT_DEPLOYMENT || ''
// Auth mode for Foundry: 'entra' (managed identity, default) or 'apikey'
const AZURE_AUTH_MODE = (process.env.AZURE_AUTH_MODE || 'entra').toLowerCase()
const AZURE_API_KEY = process.env.AZURE_API_KEY || '' // only used when AZURE_AUTH_MODE=apikey
// Token scope for Foundry / Cognitive Services
const AZURE_TOKEN_SCOPE = process.env.AZURE_TOKEN_SCOPE || 'https://cognitiveservices.azure.com/.default'

// --- Entra SSO (app login) ---
const ENTRA_TENANT_ID = process.env.ENTRA_TENANT_ID || ''
const ENTRA_CLIENT_ID = process.env.ENTRA_CLIENT_ID || ''
const ENTRA_CLIENT_SECRET = process.env.ENTRA_CLIENT_SECRET || ''
const SSO_ENABLED = Boolean(ENTRA_TENANT_ID && ENTRA_CLIENT_ID && ENTRA_CLIENT_SECRET)
const SESSION_SECRET = process.env.SESSION_SECRET || crypto.randomBytes(32).toString('hex')
const SESSION_TTL_MS = 8 * 60 * 60 * 1000 // 8h
const SESSION_COOKIE = 'ocf_session'
const OAUTH_STATE_COOKIE = 'ocf_oauth_state'
const APP_BASE_URL = (process.env.APP_BASE_URL || '').replace(/\/$/, '')

const RUNNING_STATES = new Set(['started', 'starting', 'running'])

// ---------------------------------------------------------------------------
// opencode.json (generated by setup) — read so we can validate + report.
// We do NOT need to parse it deeply; OpenCode reads it inside the sandbox.
// We DO inject it into the sandbox as OPENCODE_CONFIG_CONTENT so the agent
// defaults to the firm's Azure deployment.
// ---------------------------------------------------------------------------
function loadOpencodeConfig(): any | null {
  const p = path.join(process.cwd(), 'opencode.json')
  try {
    if (fs.existsSync(p)) return JSON.parse(fs.readFileSync(p, 'utf8'))
  } catch (e) {
    console.warn('[config] opencode.json present but unparseable:', (e as any)?.message)
  }
  return null
}

// ---------------------------------------------------------------------------
// Entra SSO: signed-cookie sessions (built-in crypto) + MSAL auth-code flow.
// ---------------------------------------------------------------------------
interface Session { oid: string; name?: string; email?: string; exp: number }

let msal: ConfidentialClientApplication | null = null
if (SSO_ENABLED) {
  msal = new ConfidentialClientApplication({
    auth: {
      clientId: ENTRA_CLIENT_ID,
      authority: `https://login.microsoftonline.com/${ENTRA_TENANT_ID}`,
      clientSecret: ENTRA_CLIENT_SECRET,
    },
  })
}

function b64url(buf: Buffer): string {
  return buf.toString('base64').replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '')
}
function b64urlDecode(s: string): Buffer {
  return Buffer.from(s.replace(/-/g, '+').replace(/_/g, '/'), 'base64')
}
function signSession(sess: Session): string {
  const payload = b64url(Buffer.from(JSON.stringify(sess)))
  const sig = b64url(crypto.createHmac('sha256', SESSION_SECRET).update(payload).digest())
  return payload + '.' + sig
}
function verifySession(token: string): Session | null {
  if (!token || token.indexOf('.') === -1) return null
  const [payload, sig] = token.split('.')
  const expected = b64url(crypto.createHmac('sha256', SESSION_SECRET).update(payload).digest())
  const a = Buffer.from(sig || ''); const b = Buffer.from(expected)
  if (a.length !== b.length || !crypto.timingSafeEqual(a, b)) return null
  try {
    const sess = JSON.parse(b64urlDecode(payload).toString()) as Session
    if (!sess.exp || sess.exp < Date.now()) return null
    return sess
  } catch { return null }
}
function parseCookies(req: Request): Record<string, string> {
  const out: Record<string, string> = {}
  const raw = req.headers.cookie
  if (!raw) return out
  raw.split(';').forEach((p) => {
    const i = p.indexOf('=')
    if (i > -1) out[p.slice(0, i).trim()] = decodeURIComponent(p.slice(i + 1).trim())
  })
  return out
}
function getSession(req: Request): Session | null {
  if (!SSO_ENABLED) return null
  return verifySession(parseCookies(req)[SESSION_COOKIE] || '')
}
function setSessionCookie(res: Response, token: string) {
  res.setHeader('Set-Cookie',
    `${SESSION_COOKIE}=${encodeURIComponent(token)}; HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age=${Math.floor(SESSION_TTL_MS / 1000)}`)
}
function clearSessionCookie(res: Response) {
  res.setHeader('Set-Cookie', `${SESSION_COOKIE}=; HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age=0`)
}
function baseUrl(req: Request): string {
  if (APP_BASE_URL) return APP_BASE_URL
  const proto = (req.headers['x-forwarded-proto'] as string) || req.protocol || 'https'
  const host = (req.headers['x-forwarded-host'] as string) || req.headers.host
  return `${proto}://${host}`
}

// Require an Entra session for protected routes when SSO is enabled.
function requireAuth(req: Request, res: Response, next: NextFunction) {
  if (!SSO_ENABLED) return next()
  const sess = getSession(req)
  if (sess) { (req as any).session = sess; return next() }
  if (req.path.startsWith('/api/')) return res.status(401).json({ error: 'Login required', loginRequired: true })
  return res.redirect('/login')
}

// ---------------------------------------------------------------------------
// Azure Foundry auth: acquire a fresh Entra token (managed identity) per launch.
// ---------------------------------------------------------------------------
let azureCred: DefaultAzureCredential | null = null
function getAzureCred(): DefaultAzureCredential {
  if (!azureCred) azureCred = new DefaultAzureCredential()
  return azureCred
}
async function getFoundryToken(): Promise<string> {
  const tok = await getAzureCred().getToken(AZURE_TOKEN_SCOPE)
  if (!tok || !tok.token) throw new Error('Failed to acquire Entra token for Foundry')
  return tok.token
}

// ---------------------------------------------------------------------------
// Daytona client (self-hosted control plane)
// ---------------------------------------------------------------------------
function daytonaClient(): Daytona {
  const opts: any = { apiKey: DAYTONA_API_KEY }
  if (DAYTONA_API_URL) opts.apiUrl = DAYTONA_API_URL
  if (DAYTONA_TARGET) opts.target = DAYTONA_TARGET
  return new Daytona(opts)
}

// In-memory map of sandboxId -> { url, createdAt, name }
const sandboxes = new Map<string, { url: string; createdAt: string; name?: string }>()

const app = express()
app.use(express.json())

// ---------------------------------------------------------------------------
// Health + identity
// ---------------------------------------------------------------------------
app.get('/healthz', (_req: Request, res: Response) => {
  res.json({
    status: 'ok',
    service: 'opencode-foundry-launcher',
    ssoEnabled: SSO_ENABLED,
    daytonaConfigured: Boolean(DAYTONA_API_KEY),
    daytonaSelfHosted: Boolean(DAYTONA_API_URL),
    foundryConfigured: Boolean(AZURE_FOUNDRY_BASE_URL && AZURE_DEFAULT_DEPLOYMENT),
    foundryAuthMode: AZURE_AUTH_MODE,
    opencodeVersion: OPENCODE_VERSION,
    activeSandboxes: sandboxes.size,
  })
})

app.get('/api/me', (req: Request, res: Response) => {
  if (!SSO_ENABLED) return res.json({ ssoEnabled: false, authed: true })
  const sess = getSession(req)
  if (!sess) return res.json({ ssoEnabled: true, authed: false })
  return res.json({ ssoEnabled: true, authed: true, name: sess.name, email: sess.email })
})

// ---------------------------------------------------------------------------
// Entra SSO routes
// ---------------------------------------------------------------------------
app.get('/login', (req: Request, res: Response) => {
  if (!SSO_ENABLED) return res.redirect('/')
  if (getSession(req)) return res.redirect('/')
  const err = typeof req.query.error === 'string' ? req.query.error : ''
  res.type('html').send(loginPage(err))
})

app.get('/auth/login', async (req: Request, res: Response) => {
  if (!SSO_ENABLED || !msal) return res.redirect('/')
  const state = b64url(crypto.randomBytes(16))
  res.setHeader('Set-Cookie', `${OAUTH_STATE_COOKIE}=${state}; HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age=600`)
  try {
    const url = await msal.getAuthCodeUrl({
      scopes: ['openid', 'profile', 'email', 'User.Read'],
      redirectUri: `${baseUrl(req)}/auth/callback`,
      state,
    })
    res.redirect(url)
  } catch (e: any) {
    res.redirect('/login?error=' + encodeURIComponent('Could not start sign-in: ' + (e?.message || e)))
  }
})

app.get('/auth/callback', async (req: Request, res: Response) => {
  if (!SSO_ENABLED || !msal) return res.redirect('/')
  const code = typeof req.query.code === 'string' ? req.query.code : ''
  const state = typeof req.query.state === 'string' ? req.query.state : ''
  const cookieState = parseCookies(req)[OAUTH_STATE_COOKIE] || ''
  if (!code || !state || state !== cookieState) {
    return res.redirect('/login?error=' + encodeURIComponent('Sign-in failed (state mismatch). Please try again.'))
  }
  try {
    const result = await msal.acquireTokenByCode({
      code,
      scopes: ['openid', 'profile', 'email', 'User.Read'],
      redirectUri: `${baseUrl(req)}/auth/callback`,
    })
    const acct = result?.account
    const claims: any = (result as any)?.idTokenClaims || {}
    const oid = acct?.homeAccountId || claims.oid || claims.sub || 'unknown'
    const name = acct?.name || claims.name
    const email = claims.preferred_username || claims.email || acct?.username
    const sess: Session = { oid, name, email, exp: Date.now() + SESSION_TTL_MS }
    setSessionCookie(res, signSession(sess))
    res.append('Set-Cookie', `${OAUTH_STATE_COOKIE}=; HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age=0`)
    console.log('[auth] sign-in ok: %s', email || oid)
    res.redirect('/')
  } catch (e: any) {
    res.redirect('/login?error=' + encodeURIComponent('Sign-in error: ' + (e?.message || e)))
  }
})

app.post('/auth/logout', (_req: Request, res: Response) => { clearSessionCookie(res); res.json({ ok: true }) })
app.get('/auth/logout', (_req: Request, res: Response) => { clearSessionCookie(res); res.redirect('/login') })

// ---------------------------------------------------------------------------
// Landing page
// ---------------------------------------------------------------------------
app.get('/', requireAuth, (_req: Request, res: Response) => {
  res.type('html').send(LANDING_HTML)
})

// ---------------------------------------------------------------------------
// Launch a sandbox running OpenCode Web, defaulted to Azure Foundry.
// ---------------------------------------------------------------------------
app.post('/api/launch', requireAuth, async (req: Request, res: Response) => {
  if (!DAYTONA_API_KEY) return res.status(500).json({ error: 'Daytona is not configured on the server. Run setup.' })
  if (!AZURE_FOUNDRY_BASE_URL || !AZURE_DEFAULT_DEPLOYMENT) {
    return res.status(500).json({ error: 'Azure Foundry is not configured on the server. Run setup.' })
  }
  const wantedName = (req.body && typeof req.body.name === 'string') ? req.body.name.trim().slice(0, 60) : ''

  const daytona = daytonaClient()
  let sandbox: Sandbox | undefined
  try {
    // Acquire a fresh Foundry token per launch (managed identity), unless using a key.
    let foundryToken = ''
    if (AZURE_AUTH_MODE === 'entra') {
      try { foundryToken = await getFoundryToken() }
      catch (e: any) { return res.status(500).json({ error: 'Could not obtain Entra token for Foundry: ' + (e?.message || e) }) }
    }

    const envVars: Record<string, string> = {}
    // OpenCode reads these for the azure provider auth.
    if (AZURE_AUTH_MODE === 'apikey') {
      if (!AZURE_API_KEY) return res.status(500).json({ error: 'AZURE_AUTH_MODE=apikey but AZURE_API_KEY is not set.' })
      envVars.AZURE_API_KEY = AZURE_API_KEY
    } else {
      // Bearer token from managed identity. OpenCode/AI-SDK can send it via the
      // azure provider's token path; we also export it for the config to read.
      envVars.AZURE_FOUNDRY_TOKEN = foundryToken
    }
    if (AZURE_FOUNDRY_BASE_URL) envVars.AZURE_FOUNDRY_BASE_URL = AZURE_FOUNDRY_BASE_URL
    if (AZURE_API_VERSION) envVars.AZURE_API_VERSION = AZURE_API_VERSION

    const labels: Record<string, string> = { app: APP_LABEL }
    if (wantedName) labels.name = wantedName

    console.log('[launch] creating sandbox%s ...', wantedName ? ` "${wantedName}"` : '')
    sandbox = await daytona.create(
      { image: SANDBOX_IMAGE, public: true, labels, envVars, resources: { cpu: 1, memory: 2, disk: 5 } },
      { timeout: 180 },
    )

    console.log('[launch] installing OpenCode...')
    await sandbox.process.executeCommand(`npm i -g opencode-ai@${OPENCODE_VERSION}`)

    // Preview URL pattern for the agent prompt.
    const previewLink = await sandbox.getPreviewLink(1234)
    const previewUrlPattern = previewLink.url.replace(/1234/, '{PORT}')

    const systemPrompt = [
      'You are running in a Daytona sandbox for an internal firm tool.',
      'Use the /home/daytona directory for file operations.',
      'This sandbox is reachable on the firm network; every port you expose has a preview URL of this form (replace {PORT}): ' + previewUrlPattern,
      'Bind servers to 0.0.0.0 and start them in the background with & , then print the preview URL for that port.',
      'git is available for local version control.',
    ].join(' ')

    // Build the OpenCode config: prefer the committed opencode.json, else assemble
    // an Azure Foundry config from env. Always set the daytona agent + default model.
    const fileCfg = loadOpencodeConfig()
    const opencodeConfig: any = fileCfg ? JSON.parse(JSON.stringify(fileCfg)) : { $schema: 'https://opencode.ai/config.json' }
    // Ensure default model + a sandbox-aware agent are present.
    if (!opencodeConfig.model && AZURE_DEFAULT_DEPLOYMENT) {
      opencodeConfig.model = 'azure/' + AZURE_DEFAULT_DEPLOYMENT
    }
    opencodeConfig.default_agent = 'daytona'
    opencodeConfig.agent = opencodeConfig.agent || {}
    opencodeConfig.agent.daytona = {
      description: 'Daytona sandbox-aware coding agent (Azure Foundry)',
      mode: 'primary',
      model: opencodeConfig.model || ('azure/' + AZURE_DEFAULT_DEPLOYMENT),
      prompt: systemPrompt,
    }

    const configJson = JSON.stringify(opencodeConfig)
    const b64 = Buffer.from(configJson).toString('base64')
    const envVar = `OPENCODE_CONFIG_CONTENT=$(echo '${b64}' | base64 -d)`

    const sessionId = `opencode-session-${Date.now()}`
    await sandbox.process.createSession(sessionId)

    // git available + identity (no GitHub account wiring — accountants don't ship code).
    await sandbox.process.executeCommand(
      `(command -v git >/dev/null 2>&1 || (apt-get update -qq && apt-get install -y -qq git >/dev/null 2>&1)); ` +
        `git config --global user.name "OpenCode"; git config --global user.email "opencode@firm.local"; ` +
        `git config --global init.defaultBranch main; git config --global --add safe.directory '*'; true`,
      undefined, undefined, 180,
    )

    // Warm up the SQLite DB (apply migrations) before the web server starts.
    console.log('[launch] warming up OpenCode DB...')
    try {
      await sandbox.process.executeCommand(
        `mkdir -p /home/daytona; cd /home/daytona; ${envVar} opencode run -m ${opencodeConfig.model} "ready" >/tmp/warmup.log 2>&1; true`,
        undefined, undefined, 120,
      )
    } catch (e: any) { console.warn('[launch] warmup non-fatal:', e?.message || e) }

    await sandbox.process.executeSessionCommand(sessionId, {
      command: `${envVar} opencode web --hostname 0.0.0.0 --port ${OPENCODE_PORT}`,
      runAsync: true,
    })

    const opencodePreviewLink = await sandbox.getPreviewLink(OPENCODE_PORT)
    const sandboxId = (sandbox as any).id ?? (sandbox as any).sandboxId ?? 'unknown'

    // Readiness: inside (port bound) then outside (proxy live).
    let webReady = false
    for (let i = 0; i < 20; i++) {
      try {
        const probe = await sandbox.process.executeCommand(
          `curl -s -o /dev/null -w "%{http_code}" --max-time 4 http://127.0.0.1:${OPENCODE_PORT}/ 2>/dev/null || echo 000`,
          undefined, undefined, 15,
        )
        if (String((probe as any).result || '').trim().split('\n').pop() === '200') { webReady = true; break }
      } catch {}
      await new Promise((r) => setTimeout(r, 2000))
    }
    let publicReady = false
    for (let i = 0; i < 20; i++) {
      try {
        const ctl = new AbortController(); const t = setTimeout(() => ctl.abort(), 6000)
        const r = await fetch(opencodePreviewLink.url, { method: 'GET', redirect: 'manual', signal: ctl.signal })
        clearTimeout(t)
        if (r.status === 200 || (r.status >= 300 && r.status < 400)) { publicReady = true; break }
      } catch {}
      await new Promise((r) => setTimeout(r, 2000))
    }

    sandboxes.set(sandboxId, { url: opencodePreviewLink.url, createdAt: new Date().toISOString(), name: wantedName || undefined })
    console.log('[launch] ready: %s (sandbox=%s)', opencodePreviewLink.url, sandboxId)
    return res.json({ ok: true, sandboxId, name: wantedName || undefined, url: opencodePreviewLink.url, webReady, publicReady })
  } catch (err: any) {
    console.error('[launch] error:', err?.message || err)
    try { if (sandbox) await sandbox.delete() } catch {}
    return res.status(500).json({ error: String(err?.message || err) })
  }
})

// ---------------------------------------------------------------------------
// Stop / status / list
// ---------------------------------------------------------------------------
app.post('/api/stop', requireAuth, async (req: Request, res: Response) => {
  if (!DAYTONA_API_KEY) return res.status(500).json({ error: 'Daytona not configured' })
  const sandboxId = (req.body && req.body.sandboxId) as string | undefined
  if (!sandboxId) return res.status(400).json({ error: 'sandboxId is required' })
  try {
    const daytona = daytonaClient()
    const sb = await (daytona as any).get(sandboxId)
    if (sb) await sb.delete()
    sandboxes.delete(sandboxId)
    return res.json({ ok: true, deleted: sandboxId })
  } catch (err: any) {
    return res.status(500).json({ error: String(err?.message || err) })
  }
})

app.get('/api/sandbox-status', requireAuth, async (req: Request, res: Response) => {
  if (!DAYTONA_API_KEY) return res.status(500).json({ error: 'Daytona not configured' })
  const id = String(req.query.id || '')
  if (!id) return res.status(400).json({ error: 'id is required' })
  const GONE = new Set(['destroying', 'destroyed', 'archived', 'archiving', 'error', 'stopped'])
  try {
    const sb = await (daytonaClient() as any).get(id)
    if (!sb) return res.json({ exists: false, gone: true, state: 'deleted' })
    const state = String((sb as any).state ?? 'unknown')
    return res.json({ exists: true, gone: GONE.has(state), state })
  } catch {
    return res.json({ exists: false, gone: true, state: 'deleted' })
  }
})

app.get('/api/sandboxes', requireAuth, async (_req: Request, res: Response) => {
  if (!DAYTONA_API_KEY) return res.status(500).json({ error: 'Daytona not configured' })
  try {
    const daytona = daytonaClient()
    const out: any[] = []
    const HIDDEN = new Set(['destroying', 'destroyed', 'archived', 'archiving', 'error'])
    for await (const sb of daytona.list({ labels: { app: APP_LABEL } } as any)) {
      const id = (sb as any).id ?? (sb as any).sandboxId
      const state = (sb as any).state ?? 'unknown'
      if (HIDDEN.has(String(state))) continue
      const labels = (sb as any).labels || {}
      let url = sandboxes.get(id)?.url || ''
      if (!url) { try { url = (await sb.getPreviewLink(OPENCODE_PORT)).url } catch {} }
      out.push({
        sandboxId: id,
        name: labels.name || sandboxes.get(id)?.name || '',
        state,
        createdAt: (sb as any).createdAt ?? null,
        running: RUNNING_STATES.has(String(state)),
        url,
        ready: false,
      })
    }
    await Promise.all(out.map(async (row) => {
      if (!row.url || !row.running) return
      try {
        const ctl = new AbortController(); const t = setTimeout(() => ctl.abort(), 3500)
        const r = await fetch(row.url, { method: 'GET', redirect: 'manual', signal: ctl.signal })
        clearTimeout(t)
        if (r.status === 200 || (r.status >= 300 && r.status < 400)) row.ready = true
      } catch {}
    }))
    out.sort((a, b) => String(b.createdAt || '').localeCompare(String(a.createdAt || '')))
    res.json({ count: out.length, sandboxes: out })
  } catch (err: any) {
    res.status(500).json({ error: String(err?.message || err) })
  }
})

app.listen(PORT, '0.0.0.0', () => {
  console.log(`opencode-foundry-launcher on 0.0.0.0:${PORT}`)
  console.log('SSO:%s | Daytona self-hosted:%s | Foundry:%s (auth=%s)',
    SSO_ENABLED, Boolean(DAYTONA_API_URL), Boolean(AZURE_FOUNDRY_BASE_URL), AZURE_AUTH_MODE)
})

// ---------------------------------------------------------------------------
// Login page (Entra SSO)
// ---------------------------------------------------------------------------
function loginPage(error: string): string {
  return `<!DOCTYPE html>
<html lang="en"><head>
<meta charset="utf-8" /><meta name="viewport" content="width=device-width, initial-scale=1" />
<title>Sign in &middot; OpenCode</title>
<link rel="icon" type="image/svg+xml" href="/favicon.svg" />
<style>
  :root { color-scheme: dark; }
  body { font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; background: #0b0d10; color: #e6e6e6; display: flex; min-height: 100vh; align-items: center; justify-content: center; margin: 0; padding: 20px; }
  .card { width: 100%; max-width: 420px; padding: 36px 32px; border: 1px solid #222; border-radius: 12px; background: #111418; text-align: center; }
  h1 { font-size: 20px; margin: 0 0 8px; }
  p { color: #9aa; font-size: 13px; line-height: 1.55; margin: 0 0 24px; }
  .ms { display: inline-flex; align-items: center; gap: 10px; background: #2f6fed; color: #fff; border: 0; padding: 12px 20px; font-size: 15px; font-weight: 700; border-radius: 8px; cursor: pointer; font-family: inherit; text-decoration: none; }
  .ms:hover { background: #2a63d4; }
  .err { color: #ff6b6b; font-size: 13px; margin-bottom: 18px; min-height: 16px; }
  .foot { color: #5a6672; font-size: 11px; margin-top: 22px; }
</style></head>
<body>
<div class="card">
  <h1>OpenCode</h1>
  <p>Sign in with your corporate Microsoft account to continue.</p>
  <div class="err">${error ? error.replace(/</g, '&lt;') : ''}</div>
  <a class="ms" href="/auth/login">Sign in with Microsoft</a>
  <div class="foot">Internal tool. Access is tied to your corporate identity.</div>
</div>
</body></html>`
}

// ---------------------------------------------------------------------------
// Favicon (inline SVG terminal mark)
// ---------------------------------------------------------------------------
const FAVICON_SVG = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><defs><linearGradient id="bg" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="#11161c"/><stop offset="1" stop-color="#0a0d10"/></linearGradient></defs><rect x="2" y="2" width="60" height="60" rx="14" fill="url(#bg)" stroke="#1f2730" stroke-width="2"/><g fill="none" stroke="#3ddc84" stroke-width="5" stroke-linecap="round" stroke-linejoin="round"><polyline points="20,22 30,32 20,42"/><line x1="36" y1="42" x2="46" y2="42"/></g></svg>`
app.get('/favicon.svg', (_req: Request, res: Response) => { res.type('image/svg+xml').set('Cache-Control', 'public, max-age=86400').send(FAVICON_SVG) })
app.get('/favicon.ico', (_req: Request, res: Response) => res.redirect(301, '/favicon.svg'))

// ---------------------------------------------------------------------------
// Landing page (stripped UI: named-sandbox launcher + running sandbox list)
// ---------------------------------------------------------------------------
const LANDING_HTML = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>OpenCode</title>
<link rel="icon" type="image/svg+xml" href="/favicon.svg" />
<style>
  :root { color-scheme: dark; }
  body { font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; background: #0b0d10; color: #e6e6e6; display: flex; min-height: 100vh; align-items: flex-start; justify-content: center; margin: 0; padding: 32px 20px; }
  .card { width: 100%; max-width: 720px; padding: 28px 32px; border: 1px solid #222; border-radius: 12px; background: #111418; }
  .topbar { display: flex; align-items: center; justify-content: space-between; margin-bottom: 6px; }
  h1 { margin: 0; font-size: 22px; }
  h2 { font-size: 13px; color: #9a9a9a; margin: 26px 0 12px; text-transform: uppercase; letter-spacing: 0.05em; }
  p { color: #aaa; line-height: 1.5; }
  .muted { color: #707070; font-size: 13px; }
  button { background: #3ddc84; color: #002; border: 0; padding: 11px 18px; font-size: 15px; border-radius: 8px; cursor: pointer; font-weight: 700; font-family: inherit; }
  button[disabled] { opacity: 0.6; cursor: wait; }
  .btn-sm { padding: 6px 12px; font-size: 13px; font-weight: 600; }
  .btn-stop { background: #ff5c5c; color: #fff; }
  .btn-ghost { background: transparent; color: #9a9a9a; border: 1px solid #333; }
  .btn-copy { background: transparent; color: #7cc5ff; border: 1px solid #2a3a48; }
  .copied { color: #3ddc84 !important; border-color: #2a4a32 !important; }
  input[type=text] { background: #0c1014; border: 1px solid #283039; color: #e6e6e6; border-radius: 8px; padding: 10px 12px; font-family: inherit; font-size: 14px; }
  input[type=text]:focus { outline: none; border-color: #3ddc84; }
  .launchbar { display: flex; gap: 10px; align-items: center; flex-wrap: wrap; }
  .launchbar input { flex: 1; min-width: 200px; }
  #out { margin-top: 18px; padding: 14px; background: #0d1115; border: 1px solid #222; border-radius: 8px; word-break: break-all; display: none; }
  a { color: #3ddc84; }
  .whoami { color: #808080; font-size: 12px; }
  .logout { background: transparent; border: 1px solid #2a3038; color: #cdd; border-radius: 8px; padding: 6px 10px; cursor: pointer; font-size: 12px; font-family: inherit; }
  .logout:hover { border-color: #3ddc84; color: #fff; }
  .row { display: flex; align-items: center; gap: 10px; padding: 12px 14px; border: 1px solid #222; border-radius: 8px; margin-bottom: 8px; background: #0d1115; }
  .row .meta { flex: 1; min-width: 0; }
  .row .nm { font-size: 15px; color: #fff; font-weight: 700; }
  .row .sub { font-size: 11px; color: #808080; margin-top: 2px; }
  .row .url { display: block; font-size: 12px; color: #3ddc84; margin-top: 5px; word-break: break-all; }
  .row .url:hover { text-decoration: underline; }
  .row .actions { display: flex; gap: 8px; align-items: center; flex-shrink: 0; }
  .pill { font-size: 10px; padding: 2px 8px; border-radius: 10px; background: #1e262e; color: #7cc5ff; }
  .pill.starting { color: #ffc857; background: #241d10; }
  .dot { display: inline-block; width: 7px; height: 7px; border-radius: 50%; margin-right: 6px; vertical-align: middle; }
  .dot.run { background: #3ddc84; } .dot.starting { background: #ffc857; } .dot.other { background: #6a7886; }
</style>
</head>
<body>
<div class="card">
  <div class="topbar">
    <h1>OpenCode</h1>
    <div style="display:flex;align-items:center;gap:10px">
      <span id="whoami" class="whoami" style="display:none"></span>
      <button id="logoutBtn" class="logout" style="display:none" onclick="logout()">Sign out</button>
    </div>
  </div>
  <p>Launch an OpenCode AI coding workspace. Give it a name so you can tell your workspaces apart, then open its link to start working.</p>

  <h2>Launch a workspace</h2>
  <div class="launchbar">
    <input id="nameInput" type="text" placeholder="Name this workspace (e.g. Q3 tax memo)" maxlength="60" />
    <button id="go" onclick="launch()">Launch</button>
  </div>
  <div id="out"></div>

  <h2>Your workspaces</h2>
  <div class="launchbar" style="margin-bottom: 12px">
    <button class="btn-sm btn-ghost" onclick="refresh()">Refresh</button>
    <span id="listStatus" class="muted"></span>
  </div>
  <div id="list"></div>
</div>
<script>
function esc(s){ return (s||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;') }
function short(id){ return (id||'').slice(0,8) }
function age(iso){ if(!iso) return ''; var s=Math.max(0,(Date.now()-new Date(iso).getTime())/1000); if(s<60) return Math.floor(s)+'s ago'; if(s<3600) return Math.floor(s/60)+'m ago'; return Math.floor(s/3600)+'h ago' }

var STOPPING = {}
var STOPPED_IDS = {}
function sleep(ms){ return new Promise(function(r){ setTimeout(r,ms) }) }

async function loadAccount(){
  try { var r=await fetch('/api/me'); var d=await r.json();
    if(d.ssoEnabled && d.authed && (d.name||d.email)){
      var who=document.getElementById('whoami'); who.textContent=d.name||d.email; who.style.display='';
      document.getElementById('logoutBtn').style.display='';
    }
  } catch(e){}
}
async function logout(){ try{ await fetch('/auth/logout',{method:'POST'}) }catch(e){} location.href='/login' }

async function launch(){
  var btn=document.getElementById('go'); var out=document.getElementById('out');
  var name=(document.getElementById('nameInput').value||'').trim();
  btn.disabled=true; btn.textContent='Launching... (~30-60s)';
  out.style.display='block'; out.textContent='Creating your workspace and starting OpenCode...';
  try{
    var r=await fetch('/api/launch',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:name})});
    var d=await r.json();
    if(!r.ok) throw new Error(d.error||'Launch failed');
    out.innerHTML='<b>'+esc(d.name||short(d.sandboxId))+'</b> is ready!<br><br><a href="'+d.url+'" target="_blank" rel="noopener">'+d.url+'</a>'+'<br><br><span class="muted">It is also listed below under <b>Your workspaces</b>.</span>';
    document.getElementById('nameInput').value='';
    btn.textContent='Launch another';
    refresh();
  }catch(e){ out.textContent='Error: '+(e.message||e); btn.textContent='Try again'; }
  finally{ btn.disabled=false; }
}

async function refresh(){
  if(Object.keys(STOPPING).length) return;
  var list=document.getElementById('list'); var status=document.getElementById('listStatus');
  status.textContent='loading...';
  try{
    var r=await fetch('/api/sandboxes'); var d=await r.json();
    if(!r.ok) throw new Error(d.error||'Failed to list');
    var raw=d.sandboxes||[];
    var returned={}; raw.forEach(function(x){ returned[x.sandboxId]=true });
    var items=raw.filter(function(x){ return !STOPPED_IDS[x.sandboxId] });
    Object.keys(STOPPED_IDS).forEach(function(id){ if(!returned[id]||(Date.now()-STOPPED_IDS[id])>120000) delete STOPPED_IDS[id] });
    status.textContent=items.length+' workspace'+(items.length===1?'':'s');
    if(!items.length){ list.innerHTML='<p class="muted">No workspaces yet. Launch one above.</p>'; return; }
    list.innerHTML=items.map(function(s){
      var title = s.name ? esc(s.name) : short(s.sandboxId);
      var dotClass=(s.running&&s.ready)?'run':(s.running?'starting':'other');
      var pill=(s.running&&!s.ready)?'<span class="pill starting">starting</span>':'<span class="pill">'+esc(s.state||'')+'</span>';
      var urlBlock, copyBtn;
      if(s.url&&s.ready){
        urlBlock='<a class="url" href="'+s.url+'" target="_blank" rel="noopener">'+s.url+'</a>';
        copyBtn='<button class="btn-sm btn-copy" onclick="copyUrl(this, \\''+s.url+'\\')">Copy link</button>';
      } else {
        urlBlock='<div class="sub" style="color:#9a9a9a">\\u23f3 Starting OpenCode\\u2026 link appears when ready</div>';
        copyBtn='<button class="btn-sm btn-copy" disabled style="opacity:.5;cursor:default">Copy link</button>';
      }
      return '<div class="row" data-sandbox="'+s.sandboxId+'">'+
        '<div class="meta">'+
          '<div class="nm"><span class="dot '+dotClass+'"></span>'+title+' '+pill+'</div>'+
          '<div class="sub">'+short(s.sandboxId)+' \\u00b7 '+age(s.createdAt)+'</div>'+
          urlBlock+
        '</div>'+
        '<div class="actions">'+copyBtn+
          '<button class="btn-sm btn-stop" onclick="stop(\\''+s.sandboxId+'\\', this)">Stop</button>'+
        '</div>'+
        '</div>';
    }).join('');
  }catch(e){ status.textContent=''; list.innerHTML='<p class="muted">Could not load workspaces: '+(e.message||e)+'</p>'; }
}

async function stop(id, btn){
  var row=document.querySelector('.row[data-sandbox="'+id+'"]');
  var label=row?(row.querySelector('.nm')?row.querySelector('.nm').textContent.trim():short(id)):short(id);
  if(!confirm('Stop and delete workspace "'+label+'"? This cannot be undone.')) return;
  btn.disabled=true; btn.textContent='Stopping...'; STOPPING[id]=true; STOPPED_IDS[id]=Date.now();
  try{
    var r=await fetch('/api/stop',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sandboxId:id})});
    var d=await r.json();
    if(!r.ok) throw new Error(d.error||'Stop failed');
    for(var i=0;i<45;i++){ await sleep(2000);
      try{ var sr=await fetch('/api/sandbox-status?id='+encodeURIComponent(id)); var sd=await sr.json(); if(sr.ok&&sd.gone) break; }catch(e){}
    }
    if(row&&row.parentNode) row.parentNode.removeChild(row);
    var listEl=document.getElementById('list'); var remaining=listEl?listEl.querySelectorAll('.row').length:0;
    document.getElementById('listStatus').textContent=remaining+' workspace'+(remaining===1?'':'s');
    if(listEl&&remaining===0) listEl.innerHTML='<p class="muted">No workspaces yet. Launch one above.</p>';
    delete STOPPING[id]; refresh();
  }catch(e){ delete STOPPING[id]; alert('Error stopping workspace: '+(e.message||e)); btn.disabled=false; btn.textContent='Stop'; }
}

function copyUrl(btn,url){
  function done(){ var p=btn.textContent; btn.textContent='Copied!'; btn.classList.add('copied'); setTimeout(function(){ btn.textContent=p; btn.classList.remove('copied') },1500) }
  if(navigator.clipboard&&navigator.clipboard.writeText){ navigator.clipboard.writeText(url).then(done).catch(function(){ window.prompt('Copy this link:',url) }) }
  else { window.prompt('Copy this link:',url) }
}

loadAccount();
refresh();
setInterval(function(){ if(!Object.keys(STOPPING).length) refresh() }, 15000);
</script>
</body>
</html>`
